name: "gitsign"
description: "Installs sigstore gitsig"

inputs:
  version:
    description: "Version to install"
    default: 0.10.1

runs:
  using: "composite"
  steps:
    - name: Download
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        mkdir -p $HOME/.bin/gitsign
        curl -L -o $HOME/.bin/gitsign/gitsign "https://github.com/sigstore/gitsign/releases/download/v${{ inputs.version }}/gitsign_${{ inputs.version }}_linux_amd64"
        chmod +x $HOME/.bin/gitsign/gitsign
        
        echo "$HOME/.bin/gitsign" >> $GITHUB_PATH
        $HOME/.bin/gitsign/gitsign version
