name: Check GitHub action pinning

on:
  push:
    paths:
      - .github/**

permissions:
  contents: read

jobs:
  pinning-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Download ratchet
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download \
            --repo sethvargo/ratchet \
            --pattern ratchet_0.5.1_linux_amd64.tar.gz v0.5.1 \
            --output ratchet_linux_amd64.tar.gz
          tar xvf ratchet_linux_amd64.tar.gz
          mkdir -p $HOME/.bin/ratchet
          mv ./ratchet $HOME/.bin/ratchet
          echo "$HOME/.bin/ratchet" >> $GITHUB_PATH
          $HOME/.bin/ratchet/ratchet -h

      - name: Check that all actions are pinned
        run: |
          make check-action-pinning
