on:
  workflow_call:
    outputs:
      digest:
        description: "Container image digest"
        value: ${{ jobs.push.outputs.digest }}

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      metadata: ${{ steps.meta.outputs.json }}
    steps:
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Image metadata
        id: meta
        uses: docker/metadata-action@dbef88086f6cef02e264edb7dbf63250c17cef6c # v5.5.0
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=

      - name: Build Image
        id: container
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker,dest=/tmp/image.tar

      - name: Image digest
        run: |
          echo "Image digest is ${{ steps.container.outputs.digest }}"
